# Generated by Django 6.0.5 on 2026-05-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDelivery',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('OrderDate', models.IntegerField()),
                ('ItemName', models.CharField()),
                ('OrderQty', models.IntegerField()),
                ('UnitPrice', models.IntegerField()),
                ('TotalAmount', models.IntegerField()),
                ('DeliveryAddress', models.CharField()),
            ],
        ),
    ]
